name: Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew build

      - name: Package with jpackage
        run: |
          mkdir dist
          jpackage ^
            --type exe ^
            --input build/libs ^
            --dest dist ^
            --name RobotConfigurationTool ^
            --main-jar Robot_Configuration_Tool-all.jar ^
            --main-class robot.configuration.Main ^
            --win-console

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobotConfigurationTool-Installer
          path: dist/*.exe

      - name: Publish Dev Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: dev-latest
          name: "Development Build"
          prerelease: true
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
