name: Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.0.0

      - name: Execute Gradle build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Package with jpackage
        run: |
          mkdir dist
          jpackage ^
            --type exe ^
            --input build/libs ^
            --dest dist ^
            --name RobotConfigurationTool ^
            --main-jar Robot_Configuration_Tool-all.jar ^
            --main-class robot.configuration.Main ^
            --win-console

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobotConfigurationTool-Installer
          path: dist/*.exe

      - name: Publish Dev Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: dev-latest
          name: "Development Build"
          prerelease: true
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
