name: Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn clean package

      - name: Get project version
        id: get_version
        shell: bash
        run: |
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Package with jpackage
        shell: cmd
        run: |
          mkdir dist
          dir target
          dir target\lib
          jpackage ^
            --type exe ^
            --input target ^
            --dest dist ^
            --name RobotConfigurationTool ^
            --main-jar Robot_Configuration_Tool-1.0.0.jar ^
            --main-class robot.configuration.main.Main ^
            --app-version 1.0.0 ^
            --vendor "BytingBulldogs" ^
            --description "Robot Configuration Tool" ^
            --icon src\main\resources\icon.ico ^
            --verbose ^
            --module-path target\lib ^
            --add-modules javafx.controls,javafx.fxml

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobotConfigurationTool
          path: dist/*.exe

      - name: Publish Dev Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: dev-latest
          name: "Development Build"
          prerelease: true
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
