name: Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn clean package

      - name: Get project version
        id: get_version
        shell: bash
        run: |
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Package with jpackage
        shell: cmd
        run: |
          mkdir dist
          jpackage --input target/app/ ^
                  --dest dist/ ^
                  --main-jar Robot_Configuration_Tool-${{ steps.get_version.outputs.version }}.jar ^
                  --main-class robot.configuration.main.Main ^
                  --name "Robot Config Tool" ^
                  --type exe ^
                  --icon src/main/resources/icon.ico ^
                  --app-version ${{ steps.get_version.outputs.version }} ^
                  --vendor "Byting Bulldogs" ^
                  --win-shortcut ^
                  --win-shortcut-prompt ^
                  --win-menu ^
                  --win-help-url https://github.com/FRC-3539/Robot_Configuration_Tool ^
                  --win-update-url https://github.com/FRC-3539/Robot_Configuration_Tool/releases

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobotConfigurationTool
          path: dist/*.exe

      - name: Publish Dev Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: dev-latest
          name: "Development Build"
          prerelease: true
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
