name: Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn clean package

      - name: Get project version
        id: get_version
        shell: bash
        run: |
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Package with jpackage
        shell: cmd
        run: |
          mkdir dist
          jpackage --input target/app/ ^
                  --dest dist/ ^
                  --main-jar Robot_Configuration_Tool-${{ steps.get_version.outputs.version }}.jar ^
                  --main-class robot.configuration.main.Main ^
                  --name "Robot Config Tool" ^
                  --type exe ^
                  --icon src/main/resources/icon.ico ^
                  --app-version ${{ steps.get_version.outputs.version }} ^
                  --vendor "Byting Bulldogs" ^
                  --win-shortcut ^
                  --win-shortcut-prompt ^
                  --win-menu ^
                  --win-help-url https://github.com/FRC-3539/Robot_Configuration_Tool ^
                  --win-update-url https://github.com/FRC-3539/Robot_Configuration_Tool/releases

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: RobotConfigurationTool
          path: dist/*.exe
  release:
    needs: [build]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Download installer artifact
        uses: actions/download-artifact@v4
        with:
          name: RobotConfigurationTool

      - name: Set Tag
        id: set_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "tag=dev-latest" >> $GITHUB_ENV
          else
            echo "tag=v" >> $GITHUB_ENV
          fi

      - name: Push to Tag
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag }}
          rm: true
          files: |
            **/*.exe
        if: github.event_name == 'push' || github.event_name == 'release'

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*.exe
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
